name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y build-essential libcurl4-openssl-dev libarchive-dev

    - name: Compile
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: tldr
        path: ./tldr

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: tldr
          path: .

      - name: Set file permissions
        run: chmod 755 ./tldr

      - name: Fetch pages
        run: ./tldr -u

      - name: Display page
        run: ./tldr cd
