name: Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y build-essential libcurl4-openssl-dev libarchive-dev

    - name: Build
      run: make

  test:
    - name: Fetch pages
      run: ./tldr -u

    - name: Display page
      run: ./tldr cd
